### ISSUE TITLE
autoencoder_training.py wrong path

### ISSUE THREAD

**Issue by GPlays09** [margitantal68/sapiagent#2]
line 81 in ^file gives ospath error, if assuming that is a typo when fixed -> sapimouse_actions/actions_3min_dx_dy_dt.csv another error occurs:

`Traceback (most recent call last):
  File "\sapiagent-master\autoencoder_training.py", line 82, in <module>
    encoder, autoencoder = train_autoencoder(df_train, stt.FEATURES, stt.DIMENSIONS, model_name, num_filters=128)
  File "\sapiagent-master\autoencoder_training.py", line 26, in train_autoencoder
    X = X.reshape(-1, input_size, input_dim)
ValueError: cannot reshape array of size 6216576 into shape (128,2)`

**Comment by GPlays09** [comment]
> 

typo*

**Comment by GPlays09** [comment]
fixed with changing `feature_type = FeatureType.DX_DY_DT` -> `feature_type = FeatureType.DX_DY` in create_sapimouse_ctions
